name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: 18.191.12.240
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            source ~/.nvm/nvm.sh

            cd /var/www/yumify

            git pull origin main

            cd server-side
            npm install

            cd ../client-side
            npm install
            npm run build

            pm2 restart yumify-server
